/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cliente.Cliente;
import fachada.Fachada;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabriel
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHomeCliente = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemHomeCliente_Buscar = new javax.swing.JMenuItem();
        jMenuItemHomeCliente_Cadastrar = new javax.swing.JMenuItem();
        jMenuItemHomeRemover = new javax.swing.JMenuItem();
        jMenuHomeLocacao = new javax.swing.JMenu();
        jMenuItemHomeLocacao_Buscar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemHomeLocacao_Atualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuHomeCliente.setText("Cliente");

        jMenuItem3.setText("Atualizar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuHomeCliente.add(jMenuItem3);

        jMenuItemHomeCliente_Buscar.setText("Buscar");
        jMenuItemHomeCliente_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeCliente_BuscarActionPerformed(evt);
            }
        });
        jMenuHomeCliente.add(jMenuItemHomeCliente_Buscar);

        jMenuItemHomeCliente_Cadastrar.setText("Cadastrar");
        jMenuItemHomeCliente_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeCliente_CadastrarActionPerformed(evt);
            }
        });
        jMenuHomeCliente.add(jMenuItemHomeCliente_Cadastrar);

        jMenuItemHomeRemover.setText("Remover");
        jMenuItemHomeRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeRemoverActionPerformed(evt);
            }
        });
        jMenuHomeCliente.add(jMenuItemHomeRemover);

        jMenuBar1.add(jMenuHomeCliente);

        jMenuHomeLocacao.setText("Locação");

        jMenuItemHomeLocacao_Buscar.setText("Buscar");
        jMenuItemHomeLocacao_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeLocacao_BuscarActionPerformed(evt);
            }
        });
        jMenuHomeLocacao.add(jMenuItemHomeLocacao_Buscar);

        jMenuItem2.setText("Cadastrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuHomeLocacao.add(jMenuItem2);

        jMenuItem1.setText("Remover");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuHomeLocacao.add(jMenuItem1);

        jMenuItemHomeLocacao_Atualizar.setText("Atualizar");
        jMenuItemHomeLocacao_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeLocacao_AtualizarActionPerformed(evt);
            }
        });
        jMenuHomeLocacao.add(jMenuItemHomeLocacao_Atualizar);

        jMenuBar1.add(jMenuHomeLocacao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemHomeCliente_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeCliente_CadastrarActionPerformed
        // TODO add your handling code here:
        //abrindo e fechando tela
        Cliente_Cadastrar cc = new Cliente_Cadastrar();
        cc.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemHomeCliente_CadastrarActionPerformed

    private void jMenuItemHomeCliente_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeCliente_BuscarActionPerformed
        // TODO add your handling code here:
        Cliente_Buscar cb = new Cliente_Buscar();
        cb.setVisible(true);
    }//GEN-LAST:event_jMenuItemHomeCliente_BuscarActionPerformed

    private void jMenuItemHomeLocacao_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeLocacao_BuscarActionPerformed
        // TODO add your handling code here:
        Locacao_Buscar lb = new Locacao_Buscar();
        lb.setVisible(true);

    }//GEN-LAST:event_jMenuItemHomeLocacao_BuscarActionPerformed

    private void jMenuItemHomeRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeRemoverActionPerformed
        // TODO add your handling code here:
        Cliente_Remover cr = new Cliente_Remover();
        cr.setVisible(true);
    }//GEN-LAST:event_jMenuItemHomeRemoverActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Locacao_Cadastrar lc = new Locacao_Cadastrar();
        lc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Locacao_Remover lr = new Locacao_Remover();
        lr.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        Cliente_Atualizar ca = new Cliente_Atualizar();
        ca.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemHomeLocacao_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeLocacao_AtualizarActionPerformed
       Locacao_Atualizar la = new Locacao_Atualizar();
       la.setVisible(true);
    }//GEN-LAST:event_jMenuItemHomeLocacao_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHomeCliente;
    private javax.swing.JMenu jMenuHomeLocacao;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemHomeCliente_Buscar;
    private javax.swing.JMenuItem jMenuItemHomeCliente_Cadastrar;
    private javax.swing.JMenuItem jMenuItemHomeLocacao_Atualizar;
    private javax.swing.JMenuItem jMenuItemHomeLocacao_Buscar;
    private javax.swing.JMenuItem jMenuItemHomeRemover;
    // End of variables declaration//GEN-END:variables
}
